"""add_legajo_field_to_profesores

Revision ID: 69bf7d8c5adf
Revises: b2bedf291c4a
Create Date: 2025-09-02 18:04:02.474911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bf7d8c5adf'
down_revision = 'b2bedf291c4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesores', sa.Column('legajo', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'profesores', ['legajo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profesores', type_='unique')
    op.drop_column('profesores', 'legajo')
    # ### end Alembic commands ###
