"""Permitir nulos en anio_perteneciente

Revision ID: b2bedf291c4a
Revises: 
Create Date: 2025-08-08 01:30:45.816317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bedf291c4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('imagen_perfil', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('login_fallidos', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.alter_column('alumnos', 'documento',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'DNI'::character varying"))
    op.alter_column('alumnos', 'nro_doc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('materiales', sa.Column('tipo', sa.String(), nullable=True))
    op.add_column('materiales', sa.Column('archivo', sa.String(), nullable=True))
    op.add_column('materiales', sa.Column('fecha_subida', sa.String(), nullable=True))
    op.add_column('materiales', sa.Column('profesor_id', sa.Integer(), nullable=True))
    op.add_column('materiales', sa.Column('materia_id', sa.Integer(), nullable=True))
    op.add_column('materiales', sa.Column('tamanio', sa.Integer(), nullable=True))
    op.add_column('materiales', sa.Column('estado', sa.String(), nullable=True))
    op.create_index(op.f('ix_materiales_id'), 'materiales', ['id'], unique=False)
    op.create_foreign_key(None, 'materiales', 'materias', ['materia_id'], ['id'])
    op.create_foreign_key(None, 'materiales', 'profesores', ['profesor_id'], ['id'])
    op.add_column('materias', sa.Column('anio_perteneciente', sa.Integer(), nullable=True))
    op.add_column('materias', sa.Column('cant_dias', sa.Integer(), nullable=True))
    op.add_column('materias', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('materias', sa.Column('creditos', sa.Integer(), nullable=True))
    op.add_column('materias', sa.Column('duracion', sa.Integer(), nullable=True))
    op.add_column('materias', sa.Column('modalidad', sa.String(), nullable=True))
    op.add_column('materias', sa.Column('profesor_responsable', sa.String(), nullable=True))
    op.add_column('materias', sa.Column('horario', sa.String(), nullable=True))
    op.add_column('materias', sa.Column('materia_previa_id', sa.Integer(), nullable=True))
    op.add_column('materias', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('materias', sa.Column('carga_horaria', sa.Integer(), nullable=True))
    op.add_column('materias', sa.Column('observaciones', sa.String(), nullable=True))
    op.create_foreign_key(None, 'materias', 'materias', ['materia_previa_id'], ['id'])
    op.add_column('profesores', sa.Column('documento', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('nro_doc', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('titulo_universitario', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('especialidad', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('fecha_alta', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('mail', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('profesores', sa.Column('mat_asignadas', sa.Integer(), nullable=True))
    op.add_column('profesores', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('profesores_legajo_key'), 'profesores', type_='unique')
    op.create_unique_constraint(None, 'profesores', ['mail'])
    op.create_unique_constraint(None, 'profesores', ['nro_doc'])
    op.create_foreign_key(None, 'profesores', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('profesores', 'legajo')
    op.add_column('tareas', sa.Column('fecha_entrega', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('fecha_publicacion', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('profesor_id', sa.Integer(), nullable=True))
    op.add_column('tareas', sa.Column('tipo', sa.String(), nullable=True))
    op.add_column('tareas', sa.Column('puntaje', sa.Integer(), nullable=True))
    op.add_column('tareas', sa.Column('estado', sa.String(), nullable=True))
    op.alter_column('tareas', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tareas_id'), 'tareas', ['id'], unique=False)
    op.create_foreign_key(None, 'tareas', 'profesores', ['profesor_id'], ['id'])
    op.drop_column('tareas', 'entregado')
    op.drop_column('tareas', 'apartado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('apartado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tareas', sa.Column('entregado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_index(op.f('ix_tareas_id'), table_name='tareas')
    op.alter_column('tareas', 'materia_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tareas', 'estado')
    op.drop_column('tareas', 'puntaje')
    op.drop_column('tareas', 'tipo')
    op.drop_column('tareas', 'profesor_id')
    op.drop_column('tareas', 'fecha_publicacion')
    op.drop_column('tareas', 'fecha_entrega')
    op.add_column('profesores', sa.Column('legajo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profesores', type_='foreignkey')
    op.drop_constraint(None, 'profesores', type_='unique')
    op.drop_constraint(None, 'profesores', type_='unique')
    op.create_unique_constraint(op.f('profesores_legajo_key'), 'profesores', ['legajo'], postgresql_nulls_not_distinct=False)
    op.drop_column('profesores', 'usuario_id')
    op.drop_column('profesores', 'mat_asignadas')
    op.drop_column('profesores', 'estado')
    op.drop_column('profesores', 'telefono')
    op.drop_column('profesores', 'mail')
    op.drop_column('profesores', 'fecha_alta')
    op.drop_column('profesores', 'especialidad')
    op.drop_column('profesores', 'titulo_universitario')
    op.drop_column('profesores', 'nro_doc')
    op.drop_column('profesores', 'documento')
    op.drop_constraint(None, 'materias', type_='foreignkey')
    op.drop_column('materias', 'observaciones')
    op.drop_column('materias', 'carga_horaria')
    op.drop_column('materias', 'estado')
    op.drop_column('materias', 'materia_previa_id')
    op.drop_column('materias', 'horario')
    op.drop_column('materias', 'profesor_responsable')
    op.drop_column('materias', 'modalidad')
    op.drop_column('materias', 'duracion')
    op.drop_column('materias', 'creditos')
    op.drop_column('materias', 'descripcion')
    op.drop_column('materias', 'cant_dias')
    op.drop_column('materias', 'anio_perteneciente')
    op.drop_constraint(None, 'materiales', type_='foreignkey')
    op.drop_constraint(None, 'materiales', type_='foreignkey')
    op.drop_index(op.f('ix_materiales_id'), table_name='materiales')
    op.drop_column('materiales', 'estado')
    op.drop_column('materiales', 'tamanio')
    op.drop_column('materiales', 'materia_id')
    op.drop_column('materiales', 'profesor_id')
    op.drop_column('materiales', 'fecha_subida')
    op.drop_column('materiales', 'archivo')
    op.drop_column('materiales', 'tipo')
    op.alter_column('alumnos', 'nro_doc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alumnos', 'documento',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'DNI'::character varying"))
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
